name: ser2net server
version: 8ff24a6
slug: ser2net
description: 'Expose serial ports over the network, including TCP and RFC2217 support

  '
url: https://github.com/vinzcoyote/addon-ha-ser2net
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
ports:
  12345/tcp: 7000
  12346/tcp: 7001
ports_description:
  12345/tcp: port to access serial device
  12346/tcp: port to access admin interface
uart: true
options:
  serial_device: /dev/ttyACM0
  network_mode: tcp
  baudrate: 115200
  data_bits: 8
  parity: none
  stop_bits: 1
  flow_control: none
  no_break: true
  max_connections: 1
  enable_admin_interface: true
schema:
  serial_device: device(subsystem=tty)
  network_mode: list(tcp|rfc2217)
  baudrate: list(9600|19200|38400|57600|115200)
  data_bits: list(5|6|7|8)
  parity: list(none|even|odd)
  stop_bits: list(1|2)
  flow_control: list(none|rtscts|xonxoff)
  no_break: bool
  max_connections: int
  enable_admin_interface: bool
image: ghcr.io/vinzcoyote/ser2net
