---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - update

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Run Repository Updater
        uses: hassio-addons/repository-updater@v11
        with:
          addon: ser2net
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
