---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - update

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Run Repository Updater
        uses: hassio-addons/repository-updater@v1
        env:
          GIT_AUTHOR_NAME: vinzcoyote
          GIT_AUTHOR_EMAIL: 41898282+vinzcoyote@users.noreply.github.com
          GIT_COMMITTER_NAME: vinzcoyote
          GIT_COMMITTER_EMAIL: 41898282+vinzcoyote@users.noreply.github.com
        with:
          addon: ser2net
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
